Repository GDSC-Hongik/gdsc-client, pull requests merged in 2024-08, with the labels that each got.

#89 [Feature]: 와우 디자인 시스템의 RainbowSpinner를 적용해요
  package.json
  pnpm-lock.yaml
  src/components/common/LoadingSpinner.tsx
  src/pages/Dashboard.tsx
  src/pages/StudentVerification.tsx
  src/pages/redirect/StudentVerificationServerRedirect.tsx
Labels: 👩‍💻 리뷰 남겨주세요!, 마감까지 D-1

#90 [Refactor]: 마이너 UI 이슈 수정
  src/components/layout/Layout.tsx
  src/pages/SignUp.tsx
Labels: 👩‍💻 리뷰 남겨주세요!, 마감까지 D-1

#88 [Refactor] : 결제 페이지에 준회원이 아닌 경우 접근하지 못하도록 해요.
  src/components/auth/guard/PaymentAccessGuard.tsx
  src/components/auth/guard/PaymentSuccessAccessGuard.tsx
  src/routes/index.tsx
Labels: 👩‍💻 리뷰 남겨주세요!, 마감까지 D-1

#91 [Refactor]: 학교 이메일 인증 정책을 변경해요
  src/components/myPage/ApproveBox.tsx
  src/components/myPage/AssociateRequirementCheck.tsx
  src/components/myPage/JoinStatus.tsx
  src/types/status.ts
  src/types/user.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 마감까지 D-1

#93 [Fix] 토스페이먼츠 QA 개선 반영
  src/hooks/mutation/usePostOrder.ts
  src/pages/PaymentsSuccess.tsx
Labels: 👩‍💻 리뷰 남겨주세요!

#87 [Fix]: 서버 로그인 로직 변경에 따른 AccessToken, RefeshToken 쿠키 세팅 제거 및 landingStatus 제거
  src/App.tsx
  src/apis/index.ts
  src/components/ApiErrorBoundary.tsx
  src/components/auth/guard/AuthAccessGuard.tsx
  src/components/auth/guard/MypageAccessGuard.tsx
  src/components/auth/guard/OnboardingClosedAccessGuard.tsx
  src/components/auth/guard/OnboardingNotOpenedAccessGuard.tsx
  src/components/auth/guard/SignupAccessGuard.tsx
  src/components/auth/guard/StudentVerificationAccessGuard.tsx
  src/components/auth/guard/index.ts
  src/components/layout/Header.tsx
  src/components/myPage/ApproveBox.tsx
  src/components/myPage/AssociateRequirementCheck.tsx
  src/components/myPage/BasicUserInfo.tsx
  src/constants/landingStatus.ts
  src/hooks/auth/useAuthToken.ts
  src/hooks/mutation/useCreateUserBasicInfo.ts
  src/hooks/zustand/useLandingStatus.ts
  src/pages/Auth.tsx
  src/pages/OnboardingClosed.tsx
  src/pages/OnboardingNotOpened.tsx
  src/pages/index.ts
  src/pages/redirect/AuthServerRedirectNavigate.tsx
  src/pages/redirect/StudentVerificationServerRedirect.tsx
  src/routes/index.tsx
  src/routes/routePath.ts
  src/utils/auth.ts
  src/utils/storage/key.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 마감 D-Day

#95 [Fix]: 0807 QA 반영
  package.json
  pnpm-lock.yaml
  src/apis/auth/authApi.ts
  src/components/bottomsheet/JoinRegularMemberBottomSheet.tsx
  src/components/myPage/ApproveBox.tsx
  src/components/myPage/BasicUserInfo.tsx
  src/components/signup/DepartmentSelect.tsx
  src/components/signup/EmailInputField.tsx
  src/hooks/auth/useStudentVerification.ts
  src/hooks/mutation/index.ts
  src/hooks/mutation/useLogout.ts
  src/pages/Auth.tsx
  src/pages/SignUp.tsx
  src/pages/StudentVerification.tsx
  src/pages/redirect/AuthServerRedirectNavigate.tsx
  src/utils/auth.ts
  src/utils/mypage/recruitmentNameFormat.ts
Labels: 👩‍💻 리뷰 남겨주세요!

#96 [Fix]: qa 반영
  src/apis/discord/discordApi.ts
  src/components/auth/guard/VerificationGuard.tsx
  src/components/discordConnect/DiscordName.tsx
  src/components/discordConnect/DiscordNickName.tsx
  src/components/discordConnect/JoinServer.tsx
  src/hooks/mutation/usePostDiscordName.ts
  src/hooks/mutation/usePostDiscordNickname.ts
  src/hooks/query/useGetDiscordJoined.ts
  src/pages/DiscordConnect.tsx
  src/routes/index.tsx
  src/utils/auth.ts
Labels: 👩‍💻 리뷰 남겨주세요!

#97 [Fix] 토스페이먼츠 쿠폰 관련 QA 사항 반영
  src/components/payments/PaymentsWidget.tsx
  src/hooks/mutation/usePostFreeOrder.ts
  src/hooks/mutation/usePostPrevOrder.ts
  src/pages/PaymentsCheckout.tsx
Labels: 👩‍💻 리뷰 남겨주세요!

#101 [Feature]: 2024-2 가입 랜딩페이지 수정
  src/App.tsx
  src/components/layout/Footer.tsx
  vite.config.ts.timestamp-1724312798440-8bfe4df2623d3.mjs
Labels: 🚧 작업 중이에요
